/bin/bash: line 1: vcf-genotype-annotator: command not found
Error in job va_annotation while creating output files /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_filtered_gt.vcf, /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_unfiltered_gt.vcf.
RuleException:
CalledProcessError in line 159 of /home/eknodel/SCC_samples/Progeny/03_variant_annotation/VEP_PVACseq_updated.snakefile:
Command '
        vcf-genotype-annotator -o /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_filtered_gt.vcf /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_filtered.vcf TUMOR 0/1;
        vcf-genotype-annotator -o /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_unfiltered_gt.vcf /scratch/eknodel/SCC_samples/Progeny/VEP/DNA_483-SC-01-B6_9-3-21_133_060_S138_L002_strelka_vep_unfiltered.vcf TUMOR 0/1;
        ' returned non-zero exit status 127
  File "/home/eknodel/SCC_samples/Progeny/03_variant_annotation/VEP_PVACseq_updated.snakefile", line 159, in __rule_va_annotation
  File "/home/eknodel/miniconda3/envs/var_call_env/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Exiting because a job execution failed. Look above for error message
